### ISSUE TITLE
Doesn't follow link?

### ISSUE THREAD

**Issue by claytonrcarter** [AsaAyers/code-links#1]
This is a great idea, a feature I had been missing, but it's not working for me.

If I open a file with, eg `const jsProcessor = require('./javascript-processor.js');` I get the blue underline in-between the single quotes, but ctrl+click only pops up my context menu.

What am I missing?

**Comment by AsaAyers** [comment]
Does ctrl+click normally open your context menu in other locations? Which OS are you running? I'm currently stuck on Windows so ctrl seemed to make sense to me, but that might need to become a setting.

**Comment by claytonrcarter** [comment]
Ah, yes, on a Mac ctrl+click opens context menu.  In Firefox, eg, I use cmd+click to open a link in a new tab.  Of course, in Atom, that's already set to create multiple cursors...  

alt+click might be an option, as it appears to be unbound (for me, at least)

FWIW I tried using `e.altKey` in my fork and it worked like a charm.

**Comment by AsaAyers** [comment]
https://github.com/AsaAyers/code-links/commit/49308760cb6a102ea75f0ef2c999ded3a47f5f5f

I can't verify it myself, but this should make it automatically switch to detecting alt when using a mac. Thanks for the report :) I just published this as v0.2.0

**Comment by claytonrcarter** [comment]
It works!  Thanks!
