### ISSUE TITLE
ES6 module support

### ISSUE THREAD

**Issue by lejafo** [AsaAyers/code-links#11]
I use babel in my project and es6 modules as well.
So, in my code I use things like this:

```
import Router from '../../common/router';
import Radio from 'backbone.radio';

import IndexRoute from './index/route';
...
```

But your plugin doesn't work for links like this. It would be great if you include this functionality in your package.

Thanks!

**Comment by AsaAyers** [comment]
yup, this is just something I haven't got to yet because I don't use modules. I am [requesting module support](https://github.com/AsaAyers/code-links/blob/master/lib/javascript-processor.js#L39) in the call to espree. PRs are always welcome if you're up for it :)

**Comment by lejafo** [comment]
I think I did it.
Just adding this code to `javascript-processor.js` `process` method:

``` javascript
const modules = ast.body.filter((el) => {
    return el.type === 'ImportDeclaration';
});

modules.map((mod) => {
    let { start, end } = mod.source.loc;
    let { value } = mod.source;

    results.push({
      moduleName: value,
      range: [
          // espree uses 1-indexed lines where
          // atom uses 0-indexed
          [start.line - 1, start.column],
          [end.line - 1, end.column]
      ]
    });
});
```

Maybe I did it in a wrong way, i don't know, but if you correct me I would be very grateful.

PS I could not PR this - says i haven't permission to repository.
PPS Sorry for my english - I'm from Russia

**Comment by AsaAyers** [comment]
Thanks. I'll verify this and get it in.

For future reference I looked up a guide from github on [contributing to open source](https://guides.github.com/activities/contributing-to-open-source/). Everyone on github can fork a repository (get your own copy), then make changes there, then issue a pull request.

**Comment by lejafo** [comment]
@AsaAyers Thanks!

**Comment by lejafo** [comment]
@AsaAyers By the way, I made PR.
