### ISSUE TITLE
Babel support

### ISSUE THREAD

**Issue by JakeGinnivan** [AsaAyers/code-links#16]
I have started using flow type attributions for a few things and code-links stops working for that file. 

It might be cool to have a babel plugin as it supports jsx and flow syntax

**Comment by AsaAyers** [comment]
Babel transpiles code, it would not be useful to code-links.

code-links is built on [espree](https://github.com/eslint/espree) which is what parses code for http://eslint.org/. They don't support flow type annotations, so code-links can't without figuring out how to swap the parser for another one.

**Comment by JakeGinnivan** [comment]
I use the `babel-eslint` parser for eslint which works great. espree is also an option for eslint. So if code-links could read the `.eslintrc` file for the configured parser that would work great?

**Comment by AsaAyers** [comment]
I'm not going to tie this to `.eslintrc` because not everyone runs eslint. I'd rather just permanently swap parsers. You're welcome to give it a shot and send a PR.

If eslint can switch back and forth maybe it's easier than I think? Either way I don't use flow and I have other projects that are more important for me to work on right now.

**Comment by JakeGinnivan** [comment]
No worries, I thought I would throw up an issue and discuss anyways. Will think on it and maybe have a look at some point

**Comment by AsaAyers** [comment]
code-links has been [deprecated](https://github.com/AsaAyers/code-links/blob/master/README.md) in favor of [js-hyperclick](https://atom.io/packages/js-hyperclick) with [hyperclick](https://atom.io/packages/hyperclick).

js-hyperclick does use babel, so it should parse any code babel can parse.
