### ISSUE TITLE
Is there any plans to support any CSS preprocessor?

### ISSUE THREAD

**Issue by battaglr** [AsaAyers/code-links#20]
Awesome plugin! Have you any plans to support Sass, or Less? That would be great.

**Comment by AsaAyers** [comment]
The purpose of this plugin was to provide a pluggable architecture and let other people provide support for other languages.

It seems like Facebook's (Hyperclick)[https://atom.io/packages/hyperclick] is supposed to do the same thing, but I haven't had time to investigate and see if I can deprecate code-links in favor of Hyperclick.

If you write a Sass or Less plugin, I don't know which would be better to write for.

**Comment by battaglr** [comment]
@AsaAyers: oh, I see. Thanks for the info. :)
