### ISSUE TITLE
Feature request: lighter style for underlines

### ISSUE THREAD

**Issue by mindrones** [AsaAyers/code-links#27]
Hi, first off thanks for this great package!

Using solid black underlines is a bit obtrusive, though: why not using dashed grey lines, or even let the user choose his/her own style?

**Comment by mindrones** [comment]
By the way, if we could choose the style for links, I'd also use a pointer as mouse icon.

**Comment by AsaAyers** [comment]
in Atom go to `Edit` > `Open Your Stylesheet`. Using https://github.com/AsaAyers/code-links/blob/master/styles/code-links.less as a template you can style it any way you like

**Comment by mindrones** [comment]
Works great, thanks a lot! 
It would be nice to have this in in the README :)
