### ISSUE TITLE
HTMLElement.shadowRoot is deprecated.

### ISSUE THREAD

**Issue by dhurbagit** [AsaAyers/code-links#29]
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `shadowRoot` and access
the editor contents directly instead.
```
HTMLElement.shadowRoot (C:\Users\DELL\AppData\Local\atom\app-1.34.0\resources\app.asar\src\text-editor-element.js:13:10)
Object.setupClickHandler (C:\Users\DELL\.atom\packages\code-links\lib\code-links.js:191:26)
<unknown> (C:\Users\DELL\.atom\packages\code-links\lib\code-links.js:78:19)
onDidAddTextEditor (<embedded>:11:428105)
Function.simpleDispatch (<embedded>:11:1172318)
Emitter.emit (<embedded>:11:1173759)
```

**Comment by AsaAyers** [comment]
See https://github.com/AsaAyers/code-links/issues/30

**Comment by dhurbagit** [comment]
how to use nested folder using @extends keyword in laravel. i have a folder like this in my project

-view
--frontend
---includes
----head.blade.php
----footer.blade.php
----header.blade.php
---pages
----template_parts
-----_info_about_blog.blade.php
-----_info_service_blog.blade.php
----home.blade.php
----about.blade.php
--default.blade.php

now i have code in this way
default.blade.php
{{---start like this---

<!DOCTYPE html>
<html lang="en">
<head>
@include('frontend.includes.head')
</head>
<body>
@include('frontend.includes.header')
@yield('body')
@include('frontend.includes.footer')
<a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>



<script src="{{url('public/frontend/lib/jquery/jquery.min.js')}}"></script>
<script src="{{url('public/frontend/lib/jquery/jquery-migrate.min.js')}}"></script>
<script src="{{url('public/frontend/lib/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<script src="{{url('public/frontend/lib/easing/easing.min.js')}}"></script>
<script src="{{url('public/frontend/lib/mobile-nav/mobile-nav.js')}}"></script>
<script src="{{url('public/frontend/lib/wow/wow.min.js')}}"></script>
<script src="{{url('public/frontend/lib/waypoints/waypoints.min.js')}}"></script>
<script src="{{url('public/frontend/lib/counterup/counterup.min.js')}}"></script>
<script src="{{url('public/frontend/lib/owlcarousel/owl.carousel.min.js')}}"></script>
<script src="{{url('public/frontend/lib/isotope/isotope.pkgd.min.js')}}"></script>
<script src="{{url('public/frontend/lib/lightbox/js/lightbox.min.js')}}"></script>

<script src="{{url('public/frontend/contactform/contactform.js')}}"></script>

<script src="{{url('public/frontend/js/main.js')}}"></script>
</body>
</html>

--}}}}}}

home.blade.php
{{--start like this

@extends('frontend.default')
@section('body')

<section id="intro" class="clearfix">
    <div class="container d-flex h-100">
        <div class="row justify-content-center align-self-center">
            <div class="col-md-6 intro-info order-md-first order-last">
                <h2>Rapid Solutions<br>for Your <span>Business!</span></h2>
                <div>
                    <a href="#about" class="btn-get-started scrollto">Get Started</a>
                </div>
            </div>

            <div class="col-md-6 intro-img order-md-last order-first">
                <img src="{{url('public/frontend/img/intro-img.svg')}}" alt="" class="img-fluid">
            </div>
        </div>
    </div>
</section>

<main id="main">
    @yield('info_about')
</main>
@endsection

}}}}}}}}


and 
_info_about_blog.blade.php

{{--start like this

@extends('frontend.pages.home')
@section('info_about')

<section id="about">

    <div class="container">
        <div class="row">

            <div class="col-lg-5 col-md-6">
                <div class="about-img">
                    <img src="{{url('public/frontend/img/about-img.jpg')}}" alt="">
                </div>
            </div>

            <div class="col-lg-7 col-md-6">
                <div class="about-content">
                    <h2>About Us</h2>
                    <h3>Odio sed id eos et laboriosam consequatur eos earum soluta.</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                    <p>Aut dolor id. Sint aliquam consequatur ex ex labore. Et quis qui dolor nulla dolores neque. Aspernatur consectetur omnis numquam quaerat. Sed fugiat nisi. Officiis veniam molestiae. Et vel ut quidem alias veritatis repudiandae ut fugit. Est ut eligendi aspernatur nulla voluptates veniam iusto vel quisquam. Fugit ut maxime incidunt accusantium totam repellendus eum error. Et repudiandae eum iste qui et ut ab alias.</p>
                    <ul>
                        <li><i class="ion-android-checkmark-circle"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>
                        <li><i class="ion-android-checkmark-circle"></i> Duis aute irure dolor in reprehenderit in voluptate velit.</li>
                        <li><i class="ion-android-checkmark-circle"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate trideta storacalaperda mastiro dolore eu fugiat nulla pariatur.</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

</section>
@endsection



}}}}}


here now for _info_about_blog.blade.php dont whow in home.blade.php. i have using @yield('info_about') in home.blade.php and. 
here i have use @extends keywords in 
_info_about_blog.blade.php
but my content _info_about_blog information dont show in home page in out put result....


how can i solve it please help me i will be so thank full to all github member please .. help me
