### ISSUE TITLE
Deprecated selector in `code-links\styles\code-links.less`

### ISSUE THREAD

**Issue by dhurbagit** [AsaAyers/code-links#30]
In `code-links\styles\code-links.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `body.code-links-visible atom-text-editor::shadow .code-links .region` => `body.code-links-visible atom-text-editor.editor .code-links .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by dhurbagit** [comment]
need support

**Comment by AsaAyers** [comment]
This project has been dead for a long time. I added this warning to the readme 3 years ago:

:rotating_light: Deprecated :rotating_light: 
==========

If you use `code-links` for scanning JavaScript and not CoffeeScript, you should uninstall it and install [`js-hyperclick`][js-hyperclick] and [hyperclick][hyperclick] instead.

[hyperclick]: https://atom.io/packages/hyperclick
[js-hyperclick]: https://atom.io/packages/js-hyperclick
