### ISSUE TITLE
web url links?

### ISSUE THREAD

**Issue by mark-hahn** [AsaAyers/code-links#4]
Would it make sense to have links to web pages using my `web-browser`?  If so can you point me to example code to add the capability?  Or someone else could add it.  (grin)  Opening a web page takes one line of code.

**Comment by AsaAyers** [comment]
yup, someone just needs to write the package that scans the code for links. Here's [coffee-links](https://atom.io/packages/coffee-links). It scans CoffeeScript but you can adapt that to scan for links.

I also anticipated this and built http/https into the core :) https://github.com/AsaAyers/code-links/blob/master/lib/code-links.js#L201-L203

**Comment by mark-hahn** [comment]
Great.  I'll submit a PR with the few lines required to open the web page
in Atom.
