### ISSUE TITLE
ctrl-clicking adds a cursor

### ISSUE THREAD

**Issue by mark-hahn** [AsaAyers/code-links#5]
Ctrl-clicking on a link adds a cursor to the document.  Maybe just stopping propagation would be enough to fix this?

**Comment by AsaAyers** [comment]
I tried `e.preventDefault();` and `e.stopPropagation();`. They don't seem to fix it. I picked the keyboard shortcut before I knew Atom did that. I am looking for a way to prevent it.

**Comment by mark-hahn** [comment]
You might switch to alt or alt-click.  There are vertical selection
packages that use alt-click but I don't know how many users there are.

**Comment by AsaAyers** [comment]
There are problems no matter what I do.
- ctrl-click brings up the context menu (right click) on a mac, so it has to be alt there
- alt-click is a shortcut for moving windows around under Linux. No application can use that.
- ctrl-click conflicts with the multiple cursors thing.

It is in the preferences so you can change it.

**Comment by AsaAyers** [comment]
This is fixed in https://github.com/AsaAyers/code-links/commit/fa7bf29ff15b822e4e41a1057b7bbe07782cea49
