### ISSUE TITLE
newbie question

### ISSUE THREAD

**Issue by mark-hahn** [AsaAyers/code-links#6]
Why is the link recognized in line 2 but not in line 1?

``` javascript
url = 'http://atom.io';
let jsProcessor = require('http://atom.io');
```

**Comment by AsaAyers** [comment]
The [javascript-processor](https://github.com/AsaAyers/code-links/blob/master/lib/javascript-processor.js) is actually parsing the document with [espree](https://github.com/eslint/espree) to generate an Abstract Syntax Tree and will link anything it finds inside a call to `require()`. It isn't really looking for URLs, it assumes what it finds will be a module to load.

**Comment by mark-hahn** [comment]
I didn't realize this only works in requires.  This should be mentioned somewhere.  Maybe "Makes parts of your code linkable " should be "Makes `require` filenames linkable '.

So when would a URL be in a require?

**Comment by AsaAyers** [comment]
Never. I'm writing the docs now.

The idea is that anyone can write a plugin that scans your file for anything it knows how to make linkable. It might make classes or functions linkable back to their definitions. Scanning `require()` is just the simplest place to start.

**Comment by mark-hahn** [comment]
>  Never.

Then you should probably trash my PR.  I had fun doing it though.

I might make a PR or plugin to look for all URLs.

**Comment by AsaAyers** [comment]
I can use the part about having `web-browser` installed :+1: 

https://github.com/AsaAyers/code-links/blob/master/docs/service_provider.md

I hope this is enough to get you going. If not, just let me know and I'll help. If you want to chat there's a link to gitter in the readme.
